{{ config(materialized='table') }}

SELECT

LOAD_DATE,

COUNT(*) AS TOTAL_PROVIDERS,

COUNT(DISTINCT State) AS TOTAL_STATES,

COUNT(DISTINCT City) AS TOTAL_CITIES,

COUNT(DISTINCT TaxonomyCode) AS TOTAL_SPECIALIZATIONS,

SUM(CASE WHEN BUSINESS_RULE_STATUS='PASS' THEN 1 ELSE 0 END) AS BUSINESS_RULE_PASS,

SUM(CASE WHEN BUSINESS_RULE_STATUS='FAIL' THEN 1 ELSE 0 END) AS BUSINESS_RULE_FAIL,

SUM(CASE WHEN DATA_QUALITY_WARNING='YES' THEN 1 ELSE 0 END) AS DATA_QUALITY_WARNINGS

FROM {{ ref('dim_provider') }}

GROUP BY LOAD_DATE

ORDER BY LOAD_DATE DESC


-- dbt run --select mart_provider_summary