# Databricks notebook source
# Import the SparkSession class.
from pyspark.sql import SparkSession

# Import Spark SQL functions required for MDM processing.

from pyspark.sql.functions import col
from pyspark.sql.functions import when
from pyspark.sql.functions import lit
from pyspark.sql.functions import current_timestamp
from pyspark.sql.functions import concat_ws
from pyspark.sql.functions import count


# Create or retrieve the active Spark Session.
spark = SparkSession.builder.getOrCreate()

# COMMAND ----------

# Read the standardized provider dataset from the Silver layer.

# Purpose : The Silver table is the input for all Gold layer processing.

silver_df = spark.table("Healthcare_MDM.silver.provider_standardized")

# COMMAND ----------

# Validate the Silver dataset.

# Purpose : Verify the standardized provider records before applying MDM business logic.

silver_df.printSchema()

silver_df.show(truncate=False)

print(f"Silver Record Count : {silver_df.count()}")

# COMMAND ----------

# Create the Gold schema.

# Purpose : Store the final Golden Records generated by the MDM process.

spark.sql("""
CREATE SCHEMA IF NOT EXISTS Healthcare_MDM.gold
""")

# COMMAND ----------

# Create the Gold working DataFrame.

# Purpose : The Gold layer starts with the standardized provider dataset received from the Silver layer.

# All business rules,
# matching,
# survivorship,
# Golden Record creation and ORIEO payload generation will be performed on this DataFrame.

gold_df = silver_df

# COMMAND ----------

# MAGIC %md
# MAGIC ### Business Rules

# COMMAND ----------

# Apply Business Rules.

# Purpose : Validate critical business attributes required before continuing MDM processing.


# BR-001 : ProviderID must exist.
# BR-002 : Provider Status must be Active.
# BR-003 : TaxonomyCode must exist.
# BR-004 : CountryCode must be US.

from pyspark.sql.functions import when
from pyspark.sql.functions import col

gold_df = (

    gold_df

    .withColumn(
        "BUSINESS_RULE_STATUS",

        when(col("ProviderID").isNull(), "FAIL")
        .when(col("Status") != "A", "FAIL")
        .when(col("TaxonomyCode").isNull(), "FAIL")      
        .when(col("CountryCode") != "US", "FAIL")
        .otherwise("PASS")

    )

    .withColumn(
        "BUSINESS_RULE_MESSAGE",

        when(col("ProviderID").isNull(), "ProviderID is missing")
        .when(col("Status") != "A", "Inactive Provider")
        .when(col("TaxonomyCode").isNull(), "TaxonomyCode is missing")
        .when(col("CountryCode") != "US", "Invalid Country")
        .otherwise("Business rules passed")
    )
)

# COMMAND ----------

# Apply Data Quality Warnings.
#
# Purpose :
#
# Populate missing FullName for Individual Providers.
# Identify optional attributes that are missing.
#
# Data Quality Warnings
#
# DQ-001 : PhoneNumber missing.
# DQ-002 : LicenseNumber missing.
# DQ-003 : Identifier missing.

from pyspark.sql.functions import col
from pyspark.sql.functions import when
from pyspark.sql.functions import concat_ws

gold_df = (

    gold_df

    # Populate FullName if missing.
    .withColumn(

        "FullName",
        when(
            (col("FullName").isNull()) | (col("FullName") == ""),
            concat_ws(

                " ",
                col("FirstName"),
                col("MiddleName"),
                col("LastName")
            )
        )
        .otherwise(col("FullName"))
    )
    # Create Data Quality Warning.
    .withColumn(

        "DATA_QUALITY_WARNING",

        when(col("PhoneNumber").isNull(), "PhoneNumber Missing")
        .when(col("LicenseNumber").isNull(), "LicenseNumber Missing")
        .when(col("Identifier").isNull(), "Identifier Missing")
        .otherwise("No Data Quality Issues")
    )
)

# COMMAND ----------

gold_df.columns

# COMMAND ----------

display(
    gold_df.select(

"ProviderID",
"FullName",
"PhoneNumber",
"LicenseNumber",
"Identifier",

"DATA_QUALITY_WARNING"
)
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Exact Matching

# COMMAND ----------

# Perform Exact Matching.

# Purpose : Identify providers having the same ProviderID.

# Exact Matching Rules : -->> EM-001 : Same ProviderID = Exact Match


from pyspark.sql.functions import count
from pyspark.sql.functions import when
from pyspark.sql.functions import col
from pyspark.sql.window import Window

provider_window = Window.partitionBy(
    "ProviderID"
)
gold_df = (
    gold_df

    .withColumn(
        "EXACT_MATCH_COUNT",count("*").over(provider_window)
    )

    .withColumn(
        "EXACT_MATCH_STATUS",when(col("EXACT_MATCH_COUNT") > 1,"MATCH")
        .otherwise(
            "UNIQUE"
        )
    )
)

# COMMAND ----------

display(
    gold_df.select(
        "ProviderID",
        "EXACT_MATCH_COUNT",
        "EXACT_MATCH_STATUS"
    )
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Fuzzy Matching 

# COMMAND ----------

# Perform Fuzzy Matching.

# Purpose : Identify candidate provider records having similar contact information.

# Current Project

# One source system (NPPES).
# Similar contact details are marked for review.
# Records are NOT merged automatically.

from pyspark.sql.functions import concat_ws
from pyspark.sql.functions import count
from pyspark.sql.functions import when
from pyspark.sql.functions import col
from pyspark.sql.window import Window

gold_df=(gold_df

.withColumn(
"FUZZY_MATCH_KEY",
concat_ws(
"|",
col("PhoneNumber"),
col("PostalCode")
)
)

)

fuzzy_window=Window.partitionBy("FUZZY_MATCH_KEY")

gold_df=(gold_df

.withColumn(
"FUZZY_MATCH_COUNT",
count("*").over(fuzzy_window)
)

.withColumn(
"FUZZY_MATCH_STATUS",
when(
col("FUZZY_MATCH_COUNT")>1,
"REVIEW"
).otherwise(
"UNIQUE"
)

)
)

# COMMAND ----------

display(
    gold_df.select(

"ProviderID",
"PhoneNumber",
"PostalCode",
"FUZZY_MATCH_KEY",
"FUZZY_MATCH_COUNT",
"FUZZY_MATCH_STATUS"
)
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Duplicate Detection

# COMMAND ----------

# Duplicate Detection.

# Purpose : Detect exact duplicate ProviderIDs.

# Same ProviderID = Duplicate.
# Different ProviderID = Unique.

from pyspark.sql.functions import count
from pyspark.sql.window import Window

duplicate_window=Window.partitionBy("ProviderID")

gold_df=(gold_df

.withColumn(
"DUPLICATE_COUNT",
count("*").over(duplicate_window)
)

.withColumn(
"DUPLICATE_STATUS",
when(
col("DUPLICATE_COUNT")>1,
"DUPLICATE"
).otherwise(
"UNIQUE"
)

)
)

# COMMAND ----------

display(
    gold_df.select(

"ProviderID",
"DUPLICATE_COUNT",
"DUPLICATE_STATUS"
)
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Survivorship

# COMMAND ----------

# Apply Survivorship Rules.

# Purpose : Select the best available provider information.

# Survivorship Rules

# SR-001 : Keep Active Provider.
# SR-002 : Keep latest LastUpdated.
# SR-003 : Prefer non-null PhoneNumber.
# SR-004 : Prefer non-null LicenseNumber.
# SR-005 : Prefer non-null Identifier.

from pyspark.sql.functions import to_date
from pyspark.sql.window import Window
from pyspark.sql.functions import row_number

gold_df=(gold_df

.withColumn(
"LastUpdatedDate",
to_date(col("LastUpdated"))
)
)
survivorship_window=Window.partitionBy(
"ProviderID"
).orderBy(
col("Status").desc(),
col("LastUpdatedDate").desc()
)

gold_df=(gold_df

.withColumn(
"SURVIVOR_RANK",
row_number().over(survivorship_window)
)

.withColumn(
"SURVIVOR_STATUS",
when(
col("SURVIVOR_RANK")==1,
"SURVIVOR"
).otherwise(
"DISCARDED"
)

)
)

# COMMAND ----------

display(
    gold_df.select(

"ProviderID",
"LastUpdated",

"SURVIVOR_RANK",
"SURVIVOR_STATUS"
)
)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Golden Record

# COMMAND ----------

# Create Golden Records.

# Purpose :Keep only the survivor record for every Provider.

golden_df=(
    gold_df
.filter(col("SURVIVOR_STATUS")=="SURVIVOR")
)

# COMMAND ----------

golden_df.count()

# COMMAND ----------

# MAGIC %md
# MAGIC ## ORIEO

# COMMAND ----------

# Prepare ORIEO Gold Output.

# Purpose : Select the business-ready provider attributes required by ORIEO.

orieo_df=(
    golden_df
    .select(

    "ProviderID",

    "FullName",

    "Credential",

    "Gender",

    "Status",

    "AddressLine1",

    "City",

    "State",

    "PostalCode",

    "CountryCode",

    "PhoneNumber",

    "TaxonomyCode",

    "LicenseNumber",

    "Identifier",

    "BUSINESS_RULE_STATUS",

    "DATA_QUALITY_WARNING"

))

# COMMAND ----------

display(orieo_df)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Gold Table 

# COMMAND ----------

# Write Golden Records into the Gold Delta Table.

orieo_df.write \
.mode("overwrite") \
.option("overwriteSchema","true") \
.format("delta") \
.saveAsTable("Healthcare_MDM.gold.provider_golden")

# COMMAND ----------

print("Gold Record Count :",orieo_df.count())

display(orieo_df)