# Databricks notebook source
# Import the SparkSession class to create and manage Spark DataFrames

from pyspark.sql import SparkSession

# Import Spark SQL functions required to build the Bronze layer

from pyspark.sql.functions import current_timestamp
from pyspark.sql.functions import current_date
from pyspark.sql.functions import lit
from pyspark.sql.functions import to_json
from pyspark.sql.functions import struct

# Create or retrieve the active Spark Session

spark = SparkSession.builder.getOrCreate()

# COMMAND ----------

# Read the processed provider JSON file stored inside the Databricks Volume.
# This file was generated by the Python extraction layer after processing
# the raw NPPES API response.

provider_df = spark.read.option(
    "multiline",
    "true"
).json("/Volumes/healthcare_mdm/bronze/bronze_files/processed/processed_response.json")

# COMMAND ----------

# Create the Bronze DataFrame from the processed provider dataset.
#
# Bronze Layer Responsibilities
#
# 1. Preserve the complete provider payload.
# 2. Convert every provider record into a single JSON document.
# 3. Add ingestion metadata.
# 4. Track the original source system.
# 5. Track the payload format.
# 6. Track the target consuming system.
#
# Metadata Columns
#
# PROVIDER_JSON
# SOURCE_SYSTEM
# PAYLOAD_FORMAT
# TARGET_SYSTEM
# LOAD_TIMESTAMP
# LOAD_DATE
# FILE_NAME
# BATCH_ID

from pyspark.sql.functions import current_timestamp
from pyspark.sql.functions import current_date
from pyspark.sql.functions import lit
from pyspark.sql.functions import to_json
from pyspark.sql.functions import struct

bronze_df = (
    provider_df
    .withColumn(
        "PROVIDER_JSON",
        to_json(
            struct(*provider_df.columns)
        )
    )

    .withColumn(
        "SOURCE_SYSTEM",
        lit("NPPES")
    )

    .withColumn(
        "PAYLOAD_FORMAT",
        lit("JSIB")
    )

    .withColumn(
        "TARGET_SYSTEM",
        lit("ORIEO")
    )

    .withColumn(
        "LOAD_TIMESTAMP",
        current_timestamp()
    )

    .withColumn(
        "LOAD_DATE",
        current_date()
    )

    .withColumn(
        "FILE_NAME",
        lit("processed_response.json")
    )

    .withColumn(
        "BATCH_ID",
        lit("BATCH_001")
    )

    .select(
        "PROVIDER_JSON",

        "SOURCE_SYSTEM",

        "PAYLOAD_FORMAT",

        "TARGET_SYSTEM",

        "LOAD_TIMESTAMP",

        "LOAD_DATE",

        "FILE_NAME",

        "BATCH_ID"

    )

)

# COMMAND ----------

# Display the Bronze DataFrame schema before loading it into the Delta table.
# This step validates the data structure and metadata columns.

bronze_df.printSchema()

# Display all Bronze records before writing them to Delta.

bronze_df.show(
    truncate=False
)

# COMMAND ----------

# Create the Bronze schema if it does not already exist.
#
# Ensure the Bronze schema is available before creating the Delta table.
#
# This command is safe to execute multiple times because IF NOT EXISTS prevents duplicate schema creation.

spark.sql("""
CREATE SCHEMA IF NOT EXISTS Healthcare_MDM.bronze
""")

# COMMAND ----------

# Write the provider records into the Bronze Delta table.
#
# 1. Persist the raw provider payload.
# 2. Store ingestion metadata.
# 3. Create the Bronze Delta table.
#
# Development Mode
# Overwrite mode replaces the existing table during development.
# In production, this will later be replaced with incremental loading.

bronze_df.write \
    .format("delta") \
    .mode("overwrite") \
    .saveAsTable(
        "Healthcare_MDM.bronze.provider_raw"
    )

# COMMAND ----------

# Read the Bronze Table 
# verifying successful dat Loading

bronze_table_df = spark.table("Healthcare_MDM.bronze.provider_raw")
bronze_table_df.show(
    truncate=False
)

# COMMAND ----------

# Read the Bronze Delta table.
#
# Purpose : Validate that all provider records have been written successfully into the Bronze layer.

bronze_table_df = spark.table("Healthcare_MDM.bronze.provider_raw")

# COMMAND ----------

# Display all provider records stored in the Bronze table.
#
# Purpose : Verify that the provider payload and metadata columns were written successfully.

bronze_table_df.show(truncate=False)

# COMMAND ----------

# Display the Bronze table schema.
#
# Purpose : Verify the data types of every metadata column and confirm the table structure.

bronze_table_df.printSchema()

# COMMAND ----------

# Display the total number of provider records.
#
# Purpose : Validate that every processed provider record has been loaded into the Bronze layer.

print(f"Bronze Record Count : {bronze_table_df.count()}")

# COMMAND ----------

# Display one complete provider payload.
#
# Purpose : Verify that the complete JSON document has been preserved without modification.

bronze_table_df.select(
    "PROVIDER_JSON"
).show(
    1,
    truncate=False
)

# COMMAND ----------

# Display ingestion metadata.
#
# Purpose : Validate auditing, lineage, payload format and target system.

bronze_table_df.select(
    "SOURCE_SYSTEM",
    "PAYLOAD_FORMAT",
    "TARGET_SYSTEM",
    "LOAD_TIMESTAMP",
    "LOAD_DATE",
    "FILE_NAME",
    "BATCH_ID"
).show(truncate=False)