name: 'healthcare_mdm_dbt'
version: '1.0.0'
config-version: 2

profile: 'healthcare_mdm_dbt'

model-paths: ["models"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_mdm_dbt:

    staging:
      +materialized: view

    dimensions:
      +materialized: table

    marts:
      +materialized: table